### ISSUE TITLE
Multiple sources in a match directive

### ISSUE THREAD

**Issue by virt0uz** [EncoreTechnologies/puppet-fluentd#13]
Hi,

It looks like the module does not support:

```
      match:
        tag_pattern: test.raw
        type: copy
        store:
          type: relabel
          label: test1
        store:
          type: relabel
          label: test2
```

https://docs.fluentd.org/configuration/routing-examples

Multiple store directives in a match requests should be permitted.

I believe this is due to the fact that we can't have 2 keys with the same name in hiera under a particular parent key as this would work

```
      match:
        tag_pattern: test.raw
        type: copy
        store111111:
          type: relabel
          label: test1
        store:
          type: relabel
          label: test2
```
but i can't do that neither:

```
fluentd::config { '100_process.conf':
    'match'  => {
      'tag_pattern' => '**',
      'type'        => copy,
      'source'      =>  [blabla],
      'source'      =>  [blabla22],
    }
  }
```

Any recommendation on how to tackle this problem?

Thank you in advance

**Comment by virt0uz** [comment]
found my answer:

```
      match:
        tag_pattern: mta.raw
        type: copy
        store:
        - type: relabel
          label: mtamapreduce
        - type: relabel
          label: mtamapreduce
```
