### ISSUE TITLE
support multiple filters for the same tag

### ISSUE THREAD

**Issue by rmacian** [EncoreTechnologies/puppet-fluentd#26]
currently I have chained filters and seems is not supported by the module. I only get the last filter defined on my config files. Example from the fluentd documentation:

```
fluentd::configs:
  'test.conf':
     config:
       filter:
         tag_pattern: foo.bar
         type: grep
         regexp1: message
       filter:
         tag_pattern: foo.bar
         type: record_transfomer
         record:
           hostname: "#host"
```
output:

```
Notice: /Stage[main]/Fluentd/Fluentd::Config[test.conf]/File[/etc/td-agent/config.d/test.conf]/content:
--- /etc/td-agent/config.d/test.conf    2022-01-20 14:38:52.733950512 +0000
+++ /tmp/puppet-file20220120-23517-blcdg2       2022-01-20 14:41:55.222687956 +0000
@@ -0,0 +1,7 @@
+# This file is managed by Puppet, do not edit manually.
+<filter foo.bar>
+  <record>
+    hostname #host
+  </record>
+  @type record_transfomer
+</filter>
Notice: /Stage[main]/Fluentd/Fluentd::Config[test.conf]/File[/etc/td-agent/config.d/test.conf]/content: current_value '{md5}d41d8cd98f00b204e9800998ecf8427e', should be '{md5}fcf4a04a643b65e0d9904613d90349fe' (noop)
```
